# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

env:
    global:
        - LATEST_DIST=xenial
        - BRANCH="$TRAVIS_BRANCH"
        - TAG="$TRAVIS_TAG"
    matrix:
        - DIST=trusty
        - DIST=xenial

script:
    - make -rj2 pre-test
    - make -rj2 build

deploy:
    provider: script
    # Apparently Travis doesn't support having multiple commands for
    # a deployment script. Also, using the literal block "|" makes Travis use
    # the "\n" literally, so it produces syntax erros. This is why we need to
    # use the regular block that merges lines and use the ";" separator between
    # different commands
    script:
        set -eux ;
        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" ;
        make -rj2 push
    skip_cleanup: true
    on:
        tags: true
